spring:
  datasource:
    url: jdbc:postgresql://dev-postgres.choyusqw2vhj.eu-west-1.rds.amazonaws.com:5432/appdb
    username: appadmin
    password: "TempPass123!"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8080
